##### Variable and Facts #####

---
- name: Playbook with variables
  hosts: linuxhosts
  vars:
    - var1: zig
    - var2: zag
  tasks:
    - name: print data
      shell: echo "{{var1}} when you should {{var2}}" > /home/rana/Desktop/vars.txt
      
 #place the variables in the placeholder.
 
 #run the playbook
 
 ansible-playbook variables.yml
 
